version: '3'

services:

  adminer:
    depends_on:
      - db
    image: adminer:4.6
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:adminer.musiqueapproximative.test"

  db:
    environment:
      MYSQL_DATABASE: musiqueapproximative
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.6
    volumes:
      - ./src/data/fixtures/musiqueapproximative.sql:/docker-entrypoint-initdb.d/musiqueapproximative.sql

  nginx:
    depends_on: 
      - php
    image: nginx:1-alpine
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:www.musiqueapproximative.test"
    volumes:
      - ./etc/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/web:/usr/local/src/app/src/web

  php:
    build:
      context: .
    command: ["/bin/sh", "-c", "ant configure -Dprofile=docker && php-fpm"]
    depends_on:
      - db
    image: constructionsincoongrues/musiqueapproximative
    volumes:
      - ./src:/usr/local/src/app/src
  
  traefik:
    command: traefik --docker --docker.exposedbydefault false
    depends_on: 
      - nginx
      - adminer
    image: traefik:1.6-alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock      