# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         Musique Approximative 
    #description:  symfony project
    #keywords:     symfony, project
    language:      fr 
    #robots:       index, follow

  stylesheets:    ["frontend/main.css?v=3"]

  javascripts:    ["http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", soundmanager2-nodebug-jsmin.js, "behaviors.js?v=7"]

  has_layout:     true
  layout:         layout

randomSuccess:
  has_layout: false
