# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/09-Cache

default:
  enabled:     false
  with_layout: true
  lifetime:    86400

# TODO
# Si on active le cache il faut :
# - nettoyer le cache de frontend depuis backend à la modification de la liste des morceaux
# - gérer l'autoplay / random 100% coté client
