# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: post, action: home }

post_oembed:
  url:  /oembed
  param: { module: post, action: oembed }

post_md5:
  url:  /post/md5/:md5sum
  param: { module: post, action: md5 }

post_show:
  url:  /post/:slug
  param: { module: post, action: show }

post_list:
  url: /posts
  param: { module: post, action: list }

post_feed:
  url: /posts/feed
  param: { module: post, action: feed }

post_next:
  url: /posts/next
  param: { module: post, action: next }

post_prev:
  url: /posts/prev
  param: { module: post, action: prev }

post_random:
  url: /posts/random
  param: { module: post, action: random }
