generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Post
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          post
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:  ~
      list:
        display: [track_title, track_author, publish_on, is_online]
      filter: 
        class: false
      form: 
        display: 
          Track: [body, track_author, track_title, track_filename]
          Publication: [publish_on, is_online]
      edit:    ~
      new:     ~
