Post:
  actAs:
    Timestampable:
    Sluggable:
      fields: [track_author, track_title]
    Searchable:
      fields: [track_author, track_title]
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
      notnull: true
    body: string
    track_title: string
    track_author: string
    track_filename: string
    track_md5: string(32)
    svn_revision: integer
    publish_on: datetime
    is_online: bool
    contributor_id: 
      type: integer(4)
      notnull: true
  relations:
    sfGuardUser:
      local: contributor_id
