Post:
  actAs:
    Timestampable:
    Sluggable:
      fields: [track_author, track_title]
      canUpdate: true
    Searchable:
      fields: [track_author, track_title]
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
      notnull: true
    body: string
    track_title: string
    track_author: string
    track_filename: string
    track_md5: string(32)
    svn_revision: integer
    publish_on: 
      type: datetime
      notnull: true 
    is_online: boolean
    contributor_id: 
      type: integer(4)
      notnull: true
  relations:
    sfGuardUser:
      local: contributor_id

UserProfile:
  columns:
    user_id:          { type: integer(4), notnull: true }
    display_name:     { type: string(255) }
    email:            { type: string(255) }
    website_url:      { type: string(255) }
  indexes:
    email_index:
      fields: [email]
      unique: true
  relations:
    sfGuardUser:
      type: one
      foreignType: one
      class: sfGuardUser
      local: user_id
      foreign: id
      onDelete: cascade
      foreignAlias: UserProfile

